services:
  # БАЗА ДАННЫХ
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: wikijs
      POSTGRES_USER: wikijs
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  # САМА ВИКИ
  wiki:
    image: requarks/wiki:2
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: ${DB_PASS}
      DB_NAME: wikijs
    # Порты наружу НЕ выставляем, их заберет Proxy Manager внутри сети Docker
    restart: unless-stopped

  # REVERSE PROXY (Твой вход в систему и SSL)
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80'   # Публичный HTTP
      - '443:443' # Публичный HTTPS
      - '81:81'   # Админка прокси (зайти по IP:81)
    volumes:
      - ./data/npm-data:/data
      - ./data/letsencrypt:/etc/letsencrypt
    restart: unless-stopped

  # СЕРВИС БЭКАПА
  db-backup:
    image: prodrigestivill/postgres-backup-local:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=wikijs
      - POSTGRES_USER=wikijs
      - POSTGRES_PASSWORD=${DB_PASS}
      - SCHEDULE=@daily        # Делать бэкап раз в сутки (в полночь)
      - BACKUP_KEEP_DAYS=7     # Хранить локально последние 7 копий
      - BACKUP_SUFFIX=.sql.gz  # Сжимать в архив для экономии места
    volumes:
      - ./data/backups:/backups
    depends_on:
      - db

